apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: is-distroless
spec:
  images:
  - glob: "**"
  authorities:
  - key:
      secretRef:
        name: cosign-distroless
